# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fix_domain_C <- function(taxa_matrix, confidence_matrix, confidence) {
    .Call(`_speedytax_fix_domain_C`, taxa_matrix, confidence_matrix, confidence)
}

fix_rdp_rest_C <- function(taxa_matrix, confidence_matrix, confidence) {
    .Call(`_speedytax_fix_rdp_rest_C`, taxa_matrix, confidence_matrix, confidence)
}

